api:
  replicaCount: 3
  image:
    repository: myregistry.io/flask-template-api
    pullPolicy: IfNotPresent

auth:
  replicaCount: 3
  image:
    repository: myregistry.io/flask-template-auth
    pullPolicy: IfNotPresent
  env:
    jwtSecret: ""

db:
  replicaCount: 1
  env:
    postgresPassword: ""
