apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: flask-template-auth:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_SECRET
